---
title: "Contig Statistical Abundance Testing"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
---
```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)

library(DESeq2)
library(tidyverse)

# define negate
'%ni%' <- Negate('%in%')

```


```{r import data}

# read in the df

coverage_df <- read.csv(file = 'corrected_coverage.tsv', sep = '\t')
colnames(coverage_df) <- gsub( "X", "", colnames(coverage_df))

# get the Patient and Dates
spl <- strsplit(as.character(colnames(coverage_df)), "_")

Patient <- sapply(spl, "[", 1)
table(Patient)
Date <- sapply(spl, "[", 2)

# set contig as rowname

rownames(coverage_df) <- coverage_df$Contig


meta_data_df <- data.frame(Patient = Patient[-1], Date = Date[-1])


patients_with_multiple_samples <- names(table(Patient)[table(Patient) > 1])
total_samples_multi_patient <- sum(table(Patient)[table(Patient) > 1])

#### calculate coefficient of variation

patient_788707_df <- coverage_df[,grepl("788707", colnames(coverage_df))]

coverage_df <- patient_788707_df


# number of samples with > 0 coverage
table(rowSums(coverage_df > 0))



# filter the contigs with 0 coverage in 0 samples

coverage_df$Contig <- NULL

head(coverage_df)

vars <- apply(coverage_df,1,var)
sdevs <- sqrt(vars)
means <- rowMeans(coverage_df)

mins <- apply(coverage_df,1,min)
maxs <- apply(coverage_df,1,max)

coeffvars <- sdevs/means

coeffvars_df <- data.frame(Contig = names(coeffvars),
                        coeffvars = coeffvars)

present_counts_df <- data.frame(Contig = names(rowSums(coverage_df > 0)),
                                counts = rowSums(coverage_df > 0))

mean_df <- data.frame(Contig = names(means),
                                means = means)

sdevs_df <- data.frame(Contig = names(sdevs),
                                sdv = sdevs)
min_df <- data.frame(Contig = names(mins),
                                min_cov = mins)
  
max_df <- data.frame(Contig = names(maxs),
                                max_cov = maxs)


coeffvars_df <- coeffvars_df %>%  
  arrange(desc(coeffvars))

combo_df <- merge(coeffvars_df, present_counts_df)

combo_df <- merge(combo_df, mean_df)

combo_df <- merge(combo_df, sdevs_df)
combo_df <- merge(combo_df, max_df)
combo_df <- merge(combo_df, min_df)

#### remove 0 hit contigs 

combo_df <- combo_df %>% filter(counts > 0)


#



ggplot(combo_df, aes(x = sdv, y = max_cov)) + 
  geom_point() + facet_wrap(~counts,  ncol = 2)

ggplot(combo_df, aes(x = coeffvars, y = max_cov)) + 
  geom_point() + 
  facet_wrap(~counts,  ncol = 2)

combo_df <- combo_df %>%  filter(coverage_df > 3)

high_cutoff_df <- combo_df %>%  filter(coeffvars > 1 & max_cov > 1000)

ggplot(high_cutoff_df, aes(x = coeffvars, y = max_cov)) + 
  geom_point() + 
  facet_wrap(~counts,  ncol = 2)


high_cutoff_contigs <- high_cutoff_df$Contig

all_contigs_one_sample_only_788707 <- combo_df %>% 
  filter(counts == 1 ) %>% 
  pull(Contig)

all_contigs_one_sample_only_788707 <- combo_df %>% 
  filter(counts == 1 ) %>% 
  pull(Contig)


four_samples_above_250meancov_less_one_coeffvar_788707 <- combo_df %>% 
  filter(counts == 4 ) %>% 
  filter(coeffvars < 1 ) %>%
  pull(Contig)

write.csv(all_contigs_one_sample_only_788707, file = "all_contigs_one_sample_only_788707.csv")

write.csv(four_samples_above_250meancov_less_one_coeffvar_788707, file = "four_samples_above_250meancov_less_one_coeffvar_788707.csv")

# 
# 
# 
# # create matrix
# 
# cts <- as.matrix(coverage_df[,-1])
# 
# 
# # factor
# 
# 
# 
# dds.overall <- DESeqDataSetFromMatrix(countData = cts,
#                               colData = meta_data_df)
# 




```